#!/usr/bin/env bash

filesystemInit() {
  hostname=$(hostname)

  zfs create -p -o mountpoint=legacy "$hostname/root"
  zfs create -p -o mountpoint=legacy "$hostname/nix"
  zfs create -p -o mountpoint=legacy "$hostname/persist"

  zfs snapshot "$hostname/root@blank"

  echo "zfs filesystem init complete"
}

filesystemMount() {
  hostname=$(hostname)

  mount -t zfs "$hostname/root" /mnt

  mkdir /mnt/nix
  mount -t zfs "$hostname/nix" /mnt/nix

  mkdir /mnt/persist
  mount -t zfs "$hostname/persist" /mnt/persist

  echo "zfs filesystem mount complete"
}

filesystemDiff() {
  zfs diff -F "$(hostname)/root@blank" | awk '{ if ($1 == "+" && $2 == "F") print $3 }'
}
