#!/bin/bash
echo "Installing packages..."
sudo add-apt-repository ppa:neovim-ppa/unstable -y
sudo apt update

sudo apt install -y zsh neovim tmux
sudo apt install ripgrep fd-find fzf cargo gcc ccls python3 python3-venv python3-pip

curl -sSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

nvm install node
npm install -g yarn
pip install --user klepto

curl --proto '=https' --tlsv1.2 -sSfL https://sh.rustup.rs -o rustup-init.sh
sh rustup-init.sh -y --default-toolchain stable

source $HOME/.cargo/env
sudo rm rustup-init.sh

cargo install tree-sitter-cli

echo "Installing Oh My Posh..."
curl -s https://ohmyposh.dev/install.sh | sudo bash -s -- -d /usr/bin
sudo chmod a+x /usr/bin/oh-my-posh

echo "Configuring zsh..."
if ! sudo usermod --shell $(which zsh) $(whoami); then
  echo "Failed to set zsh as the default shell. You may need to run chsh manually."
else
  echo "zsh has been set as the default shell."
fi

echo "Configuring Git..."
git config --global init.defaultBranch main
git config --global user.name "Rami Menai"
git config --global user.email "rami@menai.me"

echo "Cleaning files..."
if [ -f "$HOME/themes" ]; then
  sudo rm -r "$HOME/themes"
fi

echo "Setup completed successfully!"
exec zsh
