#!/bin/bash
echo "Installing packages..."
sudo apt install -y software-properties-common
sudo add-apt-repository ppa:neovim-ppa/unstable -y
sudo apt-get update

sudo apt install -y zsh neovim tmux

echo "Installing Oh My Posh..."
curl -s https://ohmyposh.dev/install.sh | sudo bash -s -- -d /usr/bin
sudo chmod a+x /usr/bin/oh-my-posh

echo "Configuring zsh..."
if ! sudo chsh -s $(which zsh); then
  echo "Failed to set zsh as the default shell. You may need to run chsh manually."
else
  echo "zsh has been set as the default shell."
fi

echo "Configuring Git..."
git config --global init.defaultBranch main
git config --global user.name "Rami Menai"
git config --global user.email "rami@menai.me"

echo "Cleaning files..."
if [ -f "$HOME/themes" ]; then
  sudo rm -r "$HOME/themes"
fi

echo "Setup completed successfully!"
