{
  imports = [
    ./networking.nix
    ./tailscale.nix
    ./bluetooth.nix
    ./openssh.nix
    ./samba.nix
    ./resolved.nix
    ./unbound.nix
    ./avahi.nix
    ./cockpit.nix
    ./syncthing.nix
    ./technitium.nix
    ./adguardhome.nix
    ./caddy.nix
    ./privatebin.nix
    ./hastebin.nix
    ./wastebin.nix
    ./shlink.nix
    ./vaultwarden.nix
    ./nullmailer.nix
    ./omnitools.nix
    ./stirlingpdf.nix
    ./cyberchef.nix
    ./searxng.nix
    ./bytestash.nix
    ./tandoor.nix
    ./picsur.nix
    ./paperless.nix
    ./calibre.nix
    ./audiobookshelf.nix
  ];
}
