{
  imports = [
    ./networking.nix
    ./tailscale.nix
    ./bluetooth.nix
    ./openssh.nix
    ./samba.nix
    ./resolved.nix
    ./unbound.nix
    ./avahi.nix
    ./cockpit.nix
    ./syncthing.nix
    ./technitium.nix
    ./adguardhome.nix
    ./caddy.nix
    ./privatebin.nix
    ./hastebin.nix
    ./wastebin.nix
    ./shlink.nix
    ./vaultwarden.nix
    ./nullmailer.nix
  ];
}
