[package]
name = "wastebin"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "wastebin"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.12.22", features = ["json", "rustls-tls"], default-features = false }
serde_json = "1.0.141"
clap = { version = "4.5.42", features = ["derive"] }
tokio = { version = "1.47.0", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.98"
arboard = { version = "3.6.0", features = ["wayland-data-control"] }
