[[session]]
name = "Sesh Config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "Tmux Config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "Neovim Config"
path = "~/.config/nvim/lua"
startup_command = "nvim core/mappings.lua"

[[session]]
name = "Zsh Config"
path = "~"
startup_command = "nvim .zshrc"

[[session]]
name = "Personal Website"
path = "~/Documents/projects/menai.me"
startup_command = "bash ~/.config/sesh/scripts/website.sh"

[[session]]
name = "School"
path = "~/Documents/projects/school"
startup_command = "bash ~/.config/sesh/scripts/school.sh"

[[session]]
name = "Test"
path = "~/Documents/sandbox"
startup_command = "bash ~/.config/sesh/scripts/test.sh"

[[session]]
name = "Advent Of Code"
path = "~/Documents/projects/aoc"
startup_command = "cd aoc/2024/day"

[[session]]
name = "LeetCode"
path = "~/Documents/sandbox"
startup_command = "bash ~/.config/sesh/scripts/leet.sh"

[[session]]
name = "Codeforces"
path = "~/Documents/sandbox/codeforces"
startup_command = "bash ~/.config/sesh/scripts/codeforces.sh"

