[[session]]
name = "Sesh Config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "Tmux Config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "Neovim Config"
path = "~/.config/nvim/lua"
startup_command = "nvim core/mappings.lua"

[[session]]
name = "Zsh Config"
path = "~"
startup_command = "nvim .zshrc"

[[session]]
name = "Notes"
path = "~/Documents/notes"
startup_command = "nvim Learning/core-principles-of-mastery.md"

[[session]]
name = "Quick Note"
path = "~/Documents/notes"
startup_command = "nvim Random/test.md --cmd 'autocmd VimEnter * ObsidianCreate'"

[[session]]
name = "Personal Website"
path = "~/Documents/menai.me"
startup_command = "bash ~/.config/sesh/scripts/website.sh"

[[session]]
name = "School"
path = "~/Documents/school"
startup_command = "bash ~/.config/sesh/scripts/school.sh"

[[session]]
name = "LeetCode"
path = "~"
startup_command = "nvim leet"

