[[session]]
name = "Sesh Config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "Tmux Config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "Neovim Config"
path = "~/.config/nvim/lua"
startup_command = "nvim core/mappings.lua"

[[session]]
name = "Zsh Config"
path = "~"
startup_command = "nvim .zshrc"

[[session]]
name = "Hyprland Config"
path = "~/.config/hypr"
startup_command = "nvim hyprland.conf"

[[session]]
name = "Wezterm Config"
path = "~/.config/wezterm"
startup_command = "nvim wezterm.lua"

[[session]]
name = "Nix Config"
path = "/etc/nixos"
startup_command = "y"

[[session]]
name = "Personal Website"
path = "~/Documents/Projects/menai.me"
startup_command = "bash ~/.config/sesh/scripts/website.sh"

[[session]]
name = "School"
path = "~/Documents/Projects/school"
startup_command = "bash ~/.config/sesh/scripts/school.sh"

[[session]]
name = "AOC"
path = "~/Documents/Projects/aoc/2024"
startup_command = "bash ~/.config/sesh/scripts/aoc.sh"

[[session]]
name = "LeetCode"
path = "~/Documents/Sandbox"
startup_command = "bash ~/.config/sesh/scripts/leet.sh"

[[session]]
name = "Codeforces"
path = "~/Documents/Projects/codeforces"
startup_command = "bash ~/.config/sesh/scripts/codeforces.sh"

