local neogit = require("neogit")

function AutoCommitCurrentFile()
  local file_path = vim.fn.expand("%:p")  -- Get the full path of the current file
  if file_path == "" then
    print('No file is currently open.')
    return
  end

  local commit_message = "Add " .. vim.fn.expand('%:t')

  -- Staging the current file
  vim.cmd("!git add " .. file_path)

  -- Committing with autogenerated message
  neogit.open({ "commit", "-m", commit_message })
end
